#!/usr/bin/python
#
#  check-vacd - Nagios monitor for vacd
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2013. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  Contacts: Andrew.McNab@cern.ch  http://www.gridpp.ac.uk/vac/
#

import os, errno, sys
import time

try:
  f = open('/var/lib/vac/counts','r')
  vm_status_line = ' (' + f.readline().strip() + ')'
  f.close()
except:
  vm_status_line = ''
  
try:
   timeout_seconds = int(sys.argv[1])
except:
   timeout_seconds = 600

# first we check the factory and give an error if there's a problem
try:
   factory_heartbeat_seconds = int(os.stat('/var/lib/vac/factory-heartbeat').st_ctime)

   if factory_heartbeat_seconds < int(time.time()) - timeout_seconds:
          print 'No vacd factory heartbeat in %.2f hours' % ((time.time() - factory_heartbeat_seconds) / 3600) + vm_status_line
          sys.exit(2)        
except:
   print 'No vacd factory heartbeat file' + vm_status_line
   sys.exit(2)

# then we check the responder and give an error if there's a problem
try:
   responder_heartbeat_seconds = int(os.stat('/var/lib/vac/responder-heartbeat').st_ctime)

   if responder_heartbeat_seconds < int(time.time()) - timeout_seconds:
          print 'No vacd responder heartbeat in %.2f hours' % ((time.time() - responder_heartbeat_seconds) / 3600) + vm_status_line
          sys.exit(2)        
except:
   print 'No vacd responder heartbeat file' + vm_status_line
   sys.exit(2)

print 'Factory + responder ok' + vm_status_line
sys.exit(0)
