#!/usr/bin/python
#
#  vac - Vac command line utility
#
#  Andrew McNab, University of Manchester.
#  Copyright (c) 2013-5. All rights reserved.
#
#  Redistribution and use in source and binary forms, with or
#  without modification, are permitted provided that the following
#  conditions are met:
#
#    o Redistributions of source code must retain the above
#      copyright notice, this list of conditions and the following
#      disclaimer. 
#    o Redistributions in binary form must reproduce the above
#      copyright notice, this list of conditions and the following
#      disclaimer in the documentation and/or other materials
#      provided with the distribution. 
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
#  CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
#  INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
#  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
#  BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
#  TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
#  ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
#  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  Contacts: Andrew.McNab@cern.ch  http://www.gridpp.ac.uk/vac/
#

import os, errno, sys
import json
import time
import socket
import shutil
import hashlib,base64
import optparse

import pprint

import vac

def vmtypesResults():
   print 'vmtypesResults()'
   
def vmtypeResults(vmtypeName):
   
   salt = base64.b64encode(os.urandom(32))
   sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
   sock.settimeout(vac.shared.udpTimeoutSeconds)
   vac.shared.setSockBufferSize(sock)

   totalcount    = 0
   runningcount  = 0
   startingcount = 0

   for factoryName in vac.shared.factories:
      try:
        sock.sendto(json.dumps({'space':vac.shared.spaceName,'cookie':hashlib.sha256(salt + factoryName).hexdigest(),
                              'method':'status'}),(factoryName,995))
      except:
        print 'Failed sending UDP query to ' + vac.shared.canonicalFQDN(factoryName)

   while True:
   
      try:
           data, addr = sock.recvfrom(10240)
                      
           try:
                response = json.loads(data)
           except:
              print 'json.loads failed for',data
              continue
                                       
           if 'space' 			in response and \
              'vmname' 			in response and \
              'cookie' 			in response and \
              'factoryname'		in response and \
              'method'			in response and \
              'state'			in response and \
              'vmtype'			in response and \
              'vmtypes'			in response and \
              vmtypeName in response['vmtypes'] and \
              response['space']  == vac.shared.spaceName and \
              response['method'] == 'status' and \
              response['cookie'] == hashlib.sha256(salt + response['factoryname']).hexdigest():
                                
                totalcount += 1
                                
                if response['vmtype'] == vmtypeName:
                  state = response['state']
                  
                  if state == vac.shared.VacState.running:
                    runningcount += 1
                  elif state == vac.shared.VacState.starting:
                    startingcount += 1

                  try:
                    if response['vmtypes'][vmtypeName]['heartbeat'] > response['vmtypes'][vmtypeName]['started']:
                    
                      cpuPercentStr = ' %5.1f%%' % ((100.0 * response['vmtypes'][vmtypeName]['cpuseconds']) / 
                                       (response['vmtypes'][vmtypeName]['heartbeat'] - response['vmtypes'][vmtypeName]['started']))
                    else:
                      cpuPercentStr = ' ------'

                    hours = (response['vmtypes'][vmtypeName]['heartbeat'] - response['vmtypes'][vmtypeName]['started']) / 3600.0

                    if state == vac.shared.VacState.running and \
                       'cpupercentage' in response['vmtypes'][response['vmtype']] and \
                       response['vmtypes'][response['vmtype']]['cpupercentage']:
                     cpuPercentageStr = '%5.1f%%' % response['vmtypes'][response['vmtype']]['cpupercentage']
                    else:
                     cpuPercentageStr = ''

                    if state == vac.shared.VacState.running and \
                       (time.time() - response['vmtypes'][response['vmtype']]['started']) > vac.shared.vmtypes[response['vmtype']]['fizzle_seconds']:
                     stateStr = '* Running  '
                    else:
                     stateStr = '  ' + state

                    print (
                            response['vmname'].split('.')[0] + ' ' + 
                            (stateStr + 12 * ' ')[:12] +
                            time.strftime(' %d/%b/%H:%M', time.localtime(response['vmtypes'][vmtypeName]['created'])) +
                            cpuPercentStr + (' %6.2fhrs  ' % hours) + (14 * ' ') +
                            cpuPercentageStr
                          )
                  except:
                    print response['vmname'].split('.')[0] + ' ' + state + ' ????'

                else:
                  state = vac.shared.VacState.shutdown
                  
                  try:

                    hours = (response['vmtypes'][vmtypeName]['heartbeat'] - response['vmtypes'][vmtypeName]['started']) / 3600.0
                  
                    if 'heartbeat' in response['vmtypes'][vmtypeName] and response['vmtypes'][vmtypeName]['heartbeat'] and \
                       response['vmtypes'][vmtypeName]['heartbeat'] > response['vmtypes'][vmtypeName]['started']:
                      cpuPercentStr = '%5.1f%%' % ((100.0 * response['vmtypes'][vmtypeName]['cpuseconds']) / 
                                       (response['vmtypes'][vmtypeName]['heartbeat'] - response['vmtypes'][vmtypeName]['started']))
                    else:
                      cpuPercentStr = '------'
                      
                    if 'messagetime' in response['vmtypes'][vmtypeName] and response['vmtypes'][vmtypeName]['messagetime']:
                      finishTime = time.strftime(' %d/%b/%H:%M  ', time.localtime(response['vmtypes'][vmtypeName]['messagetime']))
                    else:
                      finishTime = time.strftime(' %d/%b/%H:%M  ', time.localtime(response['vmtypes'][vmtypeName]['heartbeat']))
                      
                    if 'message' in response['vmtypes'][vmtypeName] and response['vmtypes'][vmtypeName]['message']:
                      message = response['vmtypes'][vmtypeName]['message']
                    else:
                      message = ''
                  
                    print (
                            response['vmname'].split('.')[0] + '   ' + state +
                            time.strftime('  %d/%b/%H:%M ', time.localtime(response['vmtypes'][vmtypeName]['created'])) +
                            cpuPercentStr + (' %6.2fhrs ' % hours) +
                            finishTime +
                            message
                          )
                  except:
                    print response['vmname'].split('.')[0] + ' ' + state + ' ????'
                                         
      except KeyboardInterrupt:
           print
           break
      except socket.error as msg:
           break

   print str(totalcount) + ' replies; ' + str(runningcount) + ' ' + vmtypeName + ' running; ' + \
                                          str(startingcount) + ' ' + vmtypeName + ' starting.'

def queryMachines(options, factoryList):

  totalCount    = 0
  runningCount  = 0
  startingCount = 0
   
  responses = vac.shared.sendMachinesRequests(factoryList)

  for factoryName in responses.keys():
    for vmName,response in responses[factoryName]['machines'].iteritems():
   
                stateStr = ('  ' + response['state'] + 10 * ' ')[0:11]

                if response['state'] == vac.shared.VacState.running:
                                       runningCount += 1
                elif response['state'] == vac.shared.VacState.starting:
                                       startingCount += 1
                totalCount += 1

                if not response['vmtype']:
                  hoursStr = 22 * ' '
                  percentStr = '      '

                elif response['state'] == vac.shared.VacState.running:
                  hoursStr = '%5.2f hrs' % ((time.time() - response['started_time']) / 3600.0)

                  if response['heartbeat_time'] > response['started_time']:
                    hoursStr += ' %0.1f%%' % (100.0 * response['cpu_seconds'] / float(response['heartbeat_time'] - response['started_time']))
                    
                  hoursStr +=  22 * ' '

                  if response['cpu_percentage'] is not None:
                    percentStr = '%5.1f%%' % response['cpu_percentage']
                  else:
                    percentStr = '      '

                elif response['state'] == vac.shared.VacState.starting:
                  hoursStr = ' %0.2f mins' % ((time.time() - response['created_time']) / 60.0) + 22 * ' '
                  percentStr = '      '

                elif response['state'] == vac.shared.VacState.shutdown and response['shutdown_message']:
                  hoursStr = '"' + response['shutdown_message'][0:19] + '"' + 22 * ' '
                  percentStr = '      '
                  
                else:
                  hoursStr = 22 * ' '
                  percentStr = '      '

                if len(response['machine'].split('.')[0]) < 15:
                 vmName = (response['machine'].split('.')[0] + 15*' ')[0:15]
                else:
                 vmName = response['machine'].split('.')[0]

                print (
                       vmName + ' ' +
                       ((response['vmtype'] + 14 * ' ') if response['vmtype'] else 10 * '-' + '    ')[0:14] + ' ' + 
                       stateStr + '  ' + 
                       hoursStr[0:21] + 
                       percentStr + 
                       ((' ' + str(response['hs06'])) if options.includeHS06 and 
                                                         response['hs06'] is not None 
                                                      else '') + 
                       ((' ' + response['vac_version']) if options.includeVersions and 
                                                       response['vac_version'] is not None 
                                                    else '')
                      )

#            print totalcount,'replies in',"%.2f" % (time.time() - start - vac.shared.udpTimeoutSeconds),'seconds;',runningcount,'running;',startingcount,'starting.'

def queryMachineType(options, machineTypeName, factoryList):

  totalCount    = 0
  runningCount  = 0
  startingCount = 0
   
  responses = vac.shared.sendVmtypesRequests(factoryList)

  for factoryName in responses.keys():
    if 'vmtypes' in responses[factoryName] and machineTypeName in responses[factoryName]['vmtypes']:
      totalCount += 1

      print (
              factoryName.split('.')[0] + ' ' + 
              str(responses[factoryName]['vmtypes'][machineTypeName]['total_hs06']) + ' ' +
              str(responses[factoryName]['vmtypes'][machineTypeName]['num_before_fizzle']) + ' ' +
              str(responses[factoryName]['vmtypes'][machineTypeName]['shutdown_time']) + ' "' +
              str(responses[factoryName]['vmtypes'][machineTypeName]['shutdown_message']) + '"'
            )

def rawFactory(factoryName):
   
   salt = base64.b64encode(os.urandom(32))
   sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
   sock.settimeout(vac.shared.udpTimeoutSeconds)
   vac.shared.setSockBufferSize(sock)

   try:
     sock.sendto(json.dumps({'space':vac.shared.spaceName,'cookie':hashlib.sha256(salt + vac.shared.canonicalFQDN(factoryName)).hexdigest(), 
                             'method':'status'}),(vac.shared.canonicalFQDN(factoryName), 995))
   except:
     print 'Failed sending UDP query to ' + vac.shared.canonicalFQDN(factoryName)

   else:
     n = 1 

     while True:
       try:
           data, addr = sock.recvfrom(10240)
                      
           try:
                response = json.loads(data)
           except:
              print 'json.loads failed for',data
              continue
              
           print '===== Begin response ' + str(n) + ' (' + str(len(data)) + ' bytes) ====='
              
           for responseKey in sorted(response.keys()):            
             print (responseKey + 15 * ' ')[:15] + " : " + str(response[responseKey])
             
           print
             
           n += 1

       except socket.error as msg:
           break

#
# PROGRAM MAIN !!!
# 

if __name__ == '__main__':

    parser = optparse.OptionParser(usage="usage: %prog [options] command [target]\n\nCommands:\n  scan\n  raw\n  vmtype")

    parser.add_option("-s", 
                      "--space",
                      dest="spaceName",
                      help="override Vac space given in configuration file")

    parser.add_option("-t", 
                      "--timeout",
                      dest="udpTimeoutSeconds", 
                      help="set timeout in seconds for UDP queries")

    parser.add_option("-H", 
                      "--include-hs06",
                      action="store_true",
                      dest="includeHS06", 
                      help="include HS06 information")

    parser.add_option("-V", 
                      "--include-versions",
                      action="store_true",
                      dest="includeVersions", 
                      help="include version information")

    parser.add_option("-l", 
                      "--legacy-proxy",
                      action="store_true",
                      dest="isLegacyProxy", 
                      help="create a legacy Globus proxy")

    parser.add_option("-c",
                      "--cert",
                      dest="certPath", 
                      help="X509 certificate file")

    parser.add_option("-k",
                      "--key",
                      dest="keyPath", 
                      help="X509 certificate's private key file")

    (options, args) = parser.parse_args()

    if len(args) > 0 and args[0]:
    
        readConfError = vac.shared.readConf()
        
        if readConfError:
# Perhaps we should try to ignore these errors in case the command
# line arguments supplement missing info in vac.conf etc? Anyway,
# for now, bad config means we do nothing.
          print 'Reading configuration fails with error: ' + readConfError
          sys.exit(1)
                
        if options.spaceName:
             vac.shared.spaceName = options.spaceName.strip()

        if options.udpTimeoutSeconds:
             vac.shared.udpTimeoutSeconds = float(options.udpTimeoutSeconds.strip())

        if args[0] == 'scan':
            print "It's  vac machines  now!"
            sys.exit(1)

        if args[0] == 'machines' and len(args) > 1:
            queryMachines(options, args[1:])
            sys.exit(0)
        elif args[0] == 'machines':
            queryMachines(options, None)
            sys.exit(0)

        if args[0] == 'machinetype' and len(args) == 2:
            queryMachineType(options, args[1], None)
            sys.exit(0)
        elif args[0] == 'machinetype' and len(args) > 2:
            queryMachineType(options, args[1], args[2:])
            sys.exit(0)
        elif args[0] == 'machinetype':
            print 'machinetype command requires an argument!'
            sys.exit(1)

# NOT UPDATED YET 
#        if args[0] == 'raw':
#            if len(args) != 2:
#              print 'raw command requires an argument!'
#              sys.exit(1)
#            else:
#              rawFactory(args[1])
#              sys.exit(0)
 
# NOT UPDATED YET 
#        if args[0] == 'vmtypes':
#            vmtypesResults()
#            sys.exit(0)

        if args[0] == 'proxy-init':
            if not options.certPath:
              print 'proxy-init command requires the --cert/-c option!'
              sys.exit(1)
            elif not options.keyPath:
              print 'proxy-init command requires the --key/-k option!'
              sys.exit(1)
            else:
              print vac.vacutils.makeX509Proxy(certPath = options.certPath, 
                                               keyPath = options.keyPath, 
                                               expirationTime = int(time.time()) + 43200, 
                                               isLegacyProxy = options.isLegacyProxy)
              sys.exit(0)

    print 'Must give command argument to vac!'
    sys.exit(1)
                                                                      