.TH VAC  "Nov 2015" "vac" "Vac Manual"
.SH NAME
.B vac
\- Vac utility command
.SH SYNOPSIS
.B vac [options] command
.SH DESCRIPTION
.B vac
is a command-line utility for querying the status of vacd(8) factory
machines.

.B Until the 1.0 release, the format of the results of this command may change without notice, and should not be relied on by other scripts etc.

.SH GENERAL OPTIONS

.HP 
.B "-h, --help"
.br
Show help message and exit

.HP 
.B "-s SPACENAME, --space=SPACENAME"
.br
Override Vac space given in the configuration file

.HP 
.B "-t UDPTIMEOUTSECONDS, --timeout=UDPTIMEOUTSECONDS"
.br
Set timeout in seconds for UDP queries

.SH COMMANDS

.HP
.B "machines [factory1] [factory2] [...]"
.br
This command uses the VacQuery UDP Protocol to contact the factory machines in this
Vac space and outputs a summary of their responses. Each line in the output
corresponds to the reported status of one virtual machine slot. This command
can be used to get a quick overview of the status of a Vac space, including 
which vmtypes are running and where, and the outcomes of virtual machines 
that are currently shut down. By default all factories in the current
space are contacted, but this can be limited to one or more by giving the
hostnames of factory machines on the command line. Hostnames will be
canonicalised if the FQDN isn't given.

If no virtual machines have run on a factory, then no responses are
returned, and at a new site you will get no output from this command
until some VMs have at least started.

.HP
.B "machinetype VMTYPE"
.br
Shows the most recent status of the given vmtype on the virtual machine
slots of all factories that respond. This includes virtual machines which
ran for this vmtype but have shut down, and will display their shutdown 
messages if available. 

.HP
.B "factories factory1 [factory2] [...]"
.br
Outputs the raw responses from one or more factory machines.

.SH CONFIGURATION FILES

The vac command uses the settings of the
.B vac.conf(5)
configuration by default, unless overriden by the command line options
described above.

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

The vac command is part of Vac: http://www.gridpp.ac.uk/vac/
.SH "SEE ALSO"
vacd(8),
vac.conf(5)
