.TH VAC  "Sep 2017" "vac" "Vac Manual"
.SH NAME
.B vac
\- Vac utility command
.SH SYNOPSIS
.B vac [options] command
.SH DESCRIPTION
.B vac
is a command-line utility for querying the status of vacd(8) factory
machines.

.B The format of the results of this command may change without notice, and should not be relied on by other scripts etc.

.SH GENERAL OPTIONS

.HP 
.B "-h, --help"
.br
Show help message and exit

.HP 
.B "-s SPACENAME, --space=SPACENAME"
.br
Override Vac space given in the configuration file

.HP 
.B "-t UDPTIMEOUTSECONDS, --timeout=UDPTIMEOUTSECONDS"
.br
Set timeout in seconds for UDP queries

.HP 
.B "-J, --json"
.br
Return output as a JSON document rather than as a list

.SH COMMANDS

.HP
.B "machines [factory1] [factory2] [...]"
.br
This command uses the VacQuery UDP Protocol to contact the factory machines in this
Vac space and outputs a summary of their responses. Each line in the output
corresponds to the reported status of one virtual machine slot. This command
can be used to get a quick overview of the status of a Vac space, including 
which machinetypes are running and where, and the outcomes of virtual machines 
that are currently shut down. By default all factories in the current
space are contacted, but this can be limited to one or more by giving the
hostnames of factory machines on the command line. Hostnames will be
canonicalised if the FQDN isn't given, and \(dq.\(dq by itself is replaced
with the local hostname.

For running machines, the time running, the lifetime CPU efficiency, and
the recent CPU efficiency are shown. The CPU efficiency is CPU time used
divided by elapsed seconds, and may be more than 100% for virtual machines
with more than one CPU.

.HP
.B "machinetype MACHINETYPE"
.br
Shows the most recent status of the given machinetype on the virtual machine
slots of all factories that respond. This includes virtual machines which
ran for this machinetype but have shut down, and will display their shutdown 
times and messages if available. Also displayed are the number and total
HS06 of running logical machiness.

.HP
.B "factories factory1 [factory2] [...]"
.br
Outputs the responses from one or more factory machines, running/total CPUs,
running/total LM slots, 15 minute CPU load average, free space on the disk(s)
containing / and /var/lib/vac, the used/total memory, and the Vac version 
of the factory. Hostnames will be canonicalised if the FQDN isn't given, and
\(dq.\(dq by itself is replaced with the local hostname.

.HP
.B "proxy-init"
.br
Requires the --cert and --key options and may take the --legacy-proxy
option. Creates a legacy Globus proxy or RFC proxy (the default.) 

.HP
.B "cernvm-signature image
.br
Outputs the CernVM metadata and signature information from an image,
indicating if the signature verification succeeded and the associated
signing X.509 DN.

.HP
.B "apel-sync [YYYYMM [YYYYMM [YYYYMM ... ]]]"
.br
Takes zero or more six digit year-month strings and writes APEL
Sync message record file(s) to today's subdirectory of 
/var/lib/vac/apel-outgoing based on the corresponding months'
records in daily subdirectories of /var/lib/vac/apel-archive . If
no year-month string is given on the command line, then the year-month
containing the time 24 hours before now is used. This means that vac
apel-sync can be run every day from cron to publish sync summaries of
the current month's progress, with a final whole-month summary being
published during the first day of the next month.

.HP
.B "squid-conf inputfile outputfile
.br
Creates a configuration file for a per-factory Squid cache using 
inputfile as a template, appending acl and cache_peer lines for
the factory FQDNs listed in the Vac configuration. The result is
only written to outputfile if the contents differ from the current
outputfile, which means the timestamp of outputfile can be checked
to see whether Squid needs to reload its configuration.

.SH CONFIGURATION FILES

The vac command uses the settings of the
.B vac.conf(5)
configuration by default, unless overriden by the command line options
described above.

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

The vac command is part of Vac: http://www.gridpp.ac.uk/vac/
.SH "SEE ALSO"
vacd(8),
vac.conf(5)
