.TH VACD 8 "Jan 2013" "vacd" "Vac Manual"
.SH NAME
.B vacd
\- Vac daemon
.SH SYNOPSIS
.B vacd
.SH DESCRIPTION
.B vacd
is a daemon which implements the Vacuum model on a factory (hypervisor) machine.

.SH CONFIGURATION FILES

See 
.B
vac.conf(5)
for a description of the file format and required options.

.SH AUTHOR
Andrew McNab <Andrew.McNab@cern.ch>

vacd is part of Vac: http://www.gridpp.ac.uk/vac/
.SH "SEE ALSO"
vac(1),
vac.conf(5)
